album/urls.py
from django.urls import path

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('nogidb.urls')),
    path('admin/', admin.site.urls, name='admin'),
] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nogidb/urls.py
from django.urls import path
from nogidb import views
from django.contrib import admin

app_name = 'nogidb'
urlpatterns = [
    path('', views.home, name='home'),
    path('list/', views.member_list, name='member_list'),
    path('list/<int:condition>/', views.condition, name='condition'),
    path('detail/<int:member_id>/', views.member_detail, name='detail'),
    path('grade/', views.grade, name='grade'),
    path('grade/<int:status>/', views.grade_condition, name='grade_condition'),
    path('admin/', admin.site.urls, name='admin')

]

nogidb/models.py
from django.db import models
from django.core import validators
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill

import pandas as pd


class Member(models.Model):

    JOIN_CLASS_CHOICES = (
        (1, '1期生'),
        (2, '2期生'),
        (3, '3期生'),
        (4, '4期生'),
    )

    ACTIVE = 0
    GRADUATE = 1

    STATUS_CHOICES = (
        (ACTIVE, '活動中'),
        (GRADUATE, '卒業生'),
    )

    name = models.CharField('名前', max_length=50)

    name_kana = models.CharField('名前（かな）', max_length=50, validators=[validators.RegexValidator(
            regex=u'^[ぁ-んァ-ンー]+$', 
            message='「名前（かな）」は、ひらがな・カタカナのみで空白を入れずに入力してください')]
    )

    birthday = models.DateField(verbose_name='生年月日', auto_now=False, auto_now_add=False)

    join_class = models.PositiveIntegerField(verbose_name='加入時期', choices=JOIN_CLASS_CHOICES)

    status = models.PositiveIntegerField('活動状況', choices=STATUS_CHOICES)

    picture = models.ImageField(verbose_name='メンバー画像', null=True, upload_to='images/')

    thumbnail = ImageSpecField(source='picture', processors=[ResizeToFill(250,330)], format='JPEG')



    def __str__(self):
        return self.name

    def status_display(self):
        if self.status == 0:
            return '活動中'
        else:
            return '卒業生'

    def join_class_display(self):
        return '{}期生'.format(self.join_class)
    
    def age(self):
        today    = int(pd.to_datetime('today').strftime('%Y%m%d'))
        birthday = int(self.birthday.strftime('%Y%m%d'))
        return int((today - birthday) / 10000)

    
    class Meta:
        db_table = 'member'
        verbose_name_plural = 'メンバー'

nogidb/forms.py
from django import forms

nogidb/views.py
from django.shortcuts import render, redirect, Http404
from django.template.response import TemplateResponse

from . import models
from album.models import Image


def home(request):
    return TemplateResponse(request, 'nogidb/home.html')

def member_list(request):
    members = models.Member.objects.all().order_by('status', 'birthday')
    return TemplateResponse(request, 'nogidb/member_list.html', {'members': members})

def condition(request, condition):
    if condition == 0:
        members = models.Member.objects.all().order_by('birthday')
    elif condition == 1:
        members = models.Member.objects.all().order_by('join_class', 'birthday')
    elif condition == 2:
        members = models.Member.objects.all().order_by('status', 'birthday')
    elif condition == 3:
        members = models.Member.objects.all().order_by('name_kana')
    else:
        return Http404
    return TemplateResponse(request, 'nogidb/member_list.html', {'members': members})

def member_detail(request, member_id):
    member = models.Member.objects.get(id=member_id)
    age = member.age() 
    return TemplateResponse(request, 'nogidb/member_detail.html', {'member': member, 'age':age})


def grade(request):
    members_1990 = models.Member.objects.filter(birthday__range=["1990-04-02", "1991-04-01"]).order_by('birthday')
    members_1991 = models.Member.objects.filter(birthday__range=["1991-04-02", "1992-04-01"]).order_by('birthday')
    members_1992 = models.Member.objects.filter(birthday__range=["1992-04-02", "1993-04-01"]).order_by('birthday')
    members_1993 = models.Member.objects.filter(birthday__range=["1993-04-02", "1994-04-01"]).order_by('birthday')
    members_1994 = models.Member.objects.filter(birthday__range=["1994-04-02", "1995-04-01"]).order_by('birthday')
    members_1995 = models.Member.objects.filter(birthday__range=["1995-04-02", "1996-04-01"]).order_by('birthday')
    members_1996 = models.Member.objects.filter(birthday__range=["1996-04-02", "1997-04-01"]).order_by('birthday')
    members_1997 = models.Member.objects.filter(birthday__range=["1997-04-02", "1998-04-01"]).order_by('birthday')
    members_1998 = models.Member.objects.filter(birthday__range=["1998-04-02", "1999-04-01"]).order_by('birthday')
    members_1999 = models.Member.objects.filter(birthday__range=["1999-04-02", "2000-04-01"]).order_by('birthday')
    members_2000 = models.Member.objects.filter(birthday__range=["2000-04-02", "2001-04-01"]).order_by('birthday')
    members_2001 = models.Member.objects.filter(birthday__range=["2001-04-02", "2002-04-01"]).order_by('birthday')
    members_2002 = models.Member.objects.filter(birthday__range=["2002-04-02", "2003-04-01"]).order_by('birthday')
    members_2003 = models.Member.objects.filter(birthday__range=["2003-04-02", "2004-04-01"]).order_by('birthday')
    members_2004 = models.Member.objects.filter(birthday__range=["2004-04-02", "2005-04-01"]).order_by('birthday')

    return TemplateResponse(
        request,
        'nogidb/grade.html',
        {
        'members_1990': members_1990,
        'members_1991': members_1991,
        'members_1992': members_1992,
        'members_1993': members_1993,
        'members_1994': members_1994,
        'members_1995': members_1995,
        'members_1996': members_1996,
        'members_1997': members_1997,
        'members_1998': members_1998,
        'members_1999': members_1999,
        'members_2000': members_2000,
        'members_2001': members_2001,
        'members_2002': members_2002,
        'members_2003': members_2003,
        'members_2004': members_2004,
        }
        )

def grade_condition(request, status):
    if status == 0:
        members = models.Member.objects.filter(status=0).order_by('birthday')
        members_1990 = members.filter(birthday__range=["1990-04-02", "1991-04-01"]).order_by('birthday')
        members_1991 = members.filter(birthday__range=["1991-04-02", "1992-04-01"]).order_by('birthday')
        members_1992 = members.filter(birthday__range=["1992-04-02", "1993-04-01"]).order_by('birthday')
        members_1993 = members.filter(birthday__range=["1993-04-02", "1994-04-01"]).order_by('birthday')
        members_1994 = members.filter(birthday__range=["1994-04-02", "1995-04-01"]).order_by('birthday')
        members_1995 = members.filter(birthday__range=["1995-04-02", "1996-04-01"]).order_by('birthday')
        members_1996 = members.filter(birthday__range=["1996-04-02", "1997-04-01"]).order_by('birthday')
        members_1997 = members.filter(birthday__range=["1997-04-02", "1998-04-01"]).order_by('birthday')
        members_1998 = members.filter(birthday__range=["1998-04-02", "1999-04-01"]).order_by('birthday')
        members_1999 = members.filter(birthday__range=["1999-04-02", "2000-04-01"]).order_by('birthday')
        members_2000 = members.filter(birthday__range=["2000-04-02", "2001-04-01"]).order_by('birthday')
        members_2001 = members.filter(birthday__range=["2001-04-02", "2002-04-01"]).order_by('birthday')
        members_2002 = members.filter(birthday__range=["2002-04-02", "2003-04-01"]).order_by('birthday')
        members_2003 = members.filter(birthday__range=["2003-04-02", "2004-04-01"]).order_by('birthday')
        members_2004 = members.filter(birthday__range=["2004-04-02", "2005-04-01"]).order_by('birthday')

    elif status == 1:
        members = models.Member.objects.filter(status=1).order_by('birthday')
        members_1990 = members.filter(birthday__range=["1990-04-02", "1991-04-01"]).order_by('birthday')
        members_1991 = members.filter(birthday__range=["1991-04-02", "1992-04-01"]).order_by('birthday')
        members_1992 = members.filter(birthday__range=["1992-04-02", "1993-04-01"]).order_by('birthday')
        members_1993 = members.filter(birthday__range=["1993-04-02", "1994-04-01"]).order_by('birthday')
        members_1994 = members.filter(birthday__range=["1994-04-02", "1995-04-01"]).order_by('birthday')
        members_1995 = members.filter(birthday__range=["1995-04-02", "1996-04-01"]).order_by('birthday')
        members_1996 = members.filter(birthday__range=["1996-04-02", "1997-04-01"]).order_by('birthday')
        members_1997 = members.filter(birthday__range=["1997-04-02", "1998-04-01"]).order_by('birthday')
        members_1998 = members.filter(birthday__range=["1998-04-02", "1999-04-01"]).order_by('birthday')
        members_1999 = members.filter(birthday__range=["1999-04-02", "2000-04-01"]).order_by('birthday')
        members_2000 = members.filter(birthday__range=["2000-04-02", "2001-04-01"]).order_by('birthday')
        members_2001 = members.filter(birthday__range=["2001-04-02", "2002-04-01"]).order_by('birthday')
        members_2002 = members.filter(birthday__range=["2002-04-02", "2003-04-01"]).order_by('birthday')
        members_2003 = members.filter(birthday__range=["2003-04-02", "2004-04-01"]).order_by('birthday')
        members_2004 = members.filter(birthday__range=["2004-04-02", "2005-04-01"]).order_by('birthday')

    
    return TemplateResponse(request, 'nogidb/grade.html',
    {
        'members_1990': members_1990,
        'members_1991': members_1991,
        'members_1992': members_1992,
        'members_1993': members_1993,
        'members_1994': members_1994,
        'members_1995': members_1995,
        'members_1996': members_1996,
        'members_1997': members_1997,
        'members_1998': members_1998,
        'members_1999': members_1999,
        'members_2000': members_2000,
        'members_2001': members_2001,
        'members_2002': members_2002,
        'members_2003': members_2003,
        'members_2004': members_2004,
        })

nogidb/templates/nogidb/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <title>乃木坂46データベース- {% block title %}{% endblock %}</title>
  <link href={% static 'css/nogidb.css' %} rel="stylesheet" type="text/css" />
  <link href="//fonts.googleapis.com/earlyaccess/nicomoji.css" rel="stylesheet" />
  {% block style %}{% endblock %}
</head>

<body>

{% block header %}
　<div class="header">
    <div class="wrapper">
      <ul>
        <li>
          <a class="brand" href={% url 'nogidb:home' %}>
            乃木坂46データベース
          </a>
        </li>

      </ul>
      <a href='/admin/'><span　id='admin'>管理画面へ</span></a>

    </div>
  </div>
{% endblock %}

<div class="wrapper">
  {% block content %}
  {% endblock %}
</div>

</body>
<footer>
<br>
<br>
<br>
</footer>
</html>

nogidb/templates/nogidb/grade.html
{% extends 'nogidb/base.html' %}
{% load staticfiles %}


{% block title %}学年別リスト{% endblock %}

{% block style %}
<link href={% static 'css/grade.css' %} rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
<h1>学年別リスト</h1>
<th><a href={% url 'nogidb:grade_condition' 0 %} >活動中のみ</a></th>
<th><a href={% url 'nogidb:grade_condition' 1 %} >卒業生のみ</a></th>
<th><a href={% url 'nogidb:grade' %} >すべて</a></th>


<h3>1990年度生まれ（29歳）</h3>
    {% for member in members_1990 %}
    <div class='grade'>
        <a href="{% url 'nogidb:detail' member.id %}">
        {% if member.thumbnail %}
        <img src='{{ member.thumbnail.url }}' alt={{ member.name }} width=50>
        {% else %}
        <img src='{{ MEDIA_URL }}images/dorayakiman.png' alt='画像はありません' width=50>
        {% endif %}
        <h4>{{ member.name }}</h4>
        </a>        
    </div>
    {% endfor %}


    <h3>1991年度生まれ（28歳）</h3>
    {% for member in members_1991 %}
    <div class='grade'>
        <a href="{% url 'nogidb:detail' member.id %}">
        {% if member.thumbnail %}
        <img src='{{ member.thumbnail.url }}' alt={{ member.name }} width=50>
        {% else %}
        <img src='{{ MEDIA_URL }}images/dorayakiman.png' alt='画像はありません' width=50>
        {% endif %}
        <h4>{{ member.name }}</h4>
        </a>        
    </div>
    {% endfor %}

    <h3>1992年度生まれ（27歳）</h3>
    {% for member in members_1992 %}
    <a href="{% url 'nogidb:detail' member.id %}">

    <div class='grade'>
        {% if member.thumbnail %}
        <img src='{{ member.thumbnail.url }}' alt={{ member.name }} width=50>
        {% else %}
        <img src='{{ MEDIA_URL }}images/dorayakiman.png' alt='画像はありません' width=50>
        {% endif %}
        <h4>{{ member.name }}</h4>
        </a>        
    </div>
    {% endfor %}

    <h3>1993年度生まれ（26歳）</h3>
    {% for member in members_1993 %}
    <div class='grade'>
        <a href="{% url 'nogidb:detail' member.id %}">
        {% if member.thumbnail %}
        <img src='{{ member.thumbnail.url }}' alt={{ member.name }} width=50>
        {% else %}
        <img src='{{ MEDIA_URL }}images/dorayakiman.png' alt='画像はありません' width=50>
        {% endif %}
        <h4>{{ member.name }}</h4>
        </a>        
    </div>
    {% endfor %}

    <h3>1994年度生まれ（25歳）</h3>
    {% for member in members_1994 %}
    <div class='grade'>
        <a href="{% url 'nogidb:detail' member.id %}">
        {% if member.thumbnail %}
        <img src='{{ member.thumbnail.url }}' alt={{ member.name }} width=50>
        {% else %}
        <img src='{{ MEDIA_URL }}images/dorayakiman.png' alt='画像はありません' width=50>
        {% endif %}
        <h4>{{ member.name }}</h4>
        </a>        
    </div>
    {% endfor %}

    <h3>1995年度生まれ（24歳）</h3>
    {% for member in members_1995 %}
    <div class='grade'>
        <a href="{% url 'nogidb:detail' member.id %}">
        {% if member.thumbnail %}
        <img src='{{ member.thumbnail.url }}' alt={{ member.name }} width=50>
        {% else %}
        <img src='{{ MEDIA_URL }}images/dorayakiman.png' alt='画像はありません' width=50>
        {% endif %}
        <h4>{{ member.name }}</h4>
        </a>        
    </div>
    {% endfor %}

    <h3>1996年度生まれ（23歳）</h3>
    {% for member in members_1996 %}
    <div class='grade'>
        <a href="{% url 'nogidb:detail' member.id %}">
        {% if member.thumbnail %}
        <img src='{{ member.thumbnail.url }}' alt={{ member.name }} width=50>
        {% else %}
        <img src='{{ MEDIA_URL }}images/dorayakiman.png' alt='画像はありません' width=50>
        {% endif %}
        <h4>{{ member.name }}</h4>
        </a>        
    </div>
    {% endfor %}

    <h3>1997年度生まれ（22歳）</h3>
    {% for member in members_1997 %}
    <div class='grade'>
        <a href="{% url 'nogidb:detail' member.id %}">
        {% if member.thumbnail %}
        <img src='{{ member.thumbnail.url }}' alt={{ member.name }} width=50>
        {% else %}
        <img src='{{ MEDIA_URL }}images/dorayakiman.png' alt='画像はありません' width=50>
        {% endif %}
        <h4>{{ member.name }}</h4>
        </a>        
    </div>
    {% endfor %}

    <h3>1998年度生まれ（21歳）</h3>
    {% for member in members_1998 %}
    <div class='grade'>
        <a href="{% url 'nogidb:detail' member.id %}">
        {% if member.thumbnail %}
        <img src='{{ member.thumbnail.url }}' alt={{ member.name }} width=50>
        {% else %}
        <img src='{{ MEDIA_URL }}images/dorayakiman.png' alt='画像はありません' width=50>
        {% endif %}
        <h4>{{ member.name }}</h4>
        </a>        
    </div>
    {% endfor %}

    <h3>1999年度生まれ（20歳）</h3>
    {% for member in members_1999 %}
    <div class='grade'>
        <a href="{% url 'nogidb:detail' member.id %}">
        {% if member.thumbnail %}
        <img src='{{ member.thumbnail.url }}' alt={{ member.name }} width=50>
        {% else %}
        <img src='{{ MEDIA_URL }}images/dorayakiman.png' alt='画像はありません' width=50>
        {% endif %}
        <h4>{{ member.name }}</h4>
        </a>        
    </div>
    {% endfor %}

    <h3>2000年度生まれ（19歳）</h3>
    {% for member in members_2000 %}
    <div class='grade'>
        <a href="{% url 'nogidb:detail' member.id %}">
        {% if member.thumbnail %}
        <img src='{{ member.thumbnail.url }}' alt={{ member.name }} width=50>
        {% else %}
        <img src='{{ MEDIA_URL }}images/dorayakiman.png' alt='画像はありません' width=50>
        {% endif %}
        <h4>{{ member.name }}</h4>
        </a>        
    </div>
    {% endfor %}

    <h3>2001年度生まれ（18歳）</h3>
    {% for member in members_2001 %}
    <div class='grade'>
        <a href="{% url 'nogidb:detail' member.id %}">
        {% if member.thumbnail %}
        <img src='{{ member.thumbnail.url }}' alt={{ member.name }} width=50>
        {% else %}
        <img src='{{ MEDIA_URL }}images/dorayakiman.png' alt='画像はありません' width=50>
        {% endif %}
        <h4>{{ member.name }}</h4>
        </a>        
    </div>
    {% endfor %}

    <h3>2002年度生まれ（17歳）</h3>
    {% for member in members_2002 %}
    <div class='grade'>
        <a href="{% url 'nogidb:detail' member.id %}">
        {% if member.thumbnail %}
        <img src='{{ member.thumbnail.url }}' alt={{ member.name }} width=50>
        {% else %}
        <img src='{{ MEDIA_URL }}images/dorayakiman.png' alt='画像はありません' width=50>
        {% endif %}
        <h4>{{ member.name }}</h4>
        </a>        
    </div>
    {% endfor %}

    <h3>2003年度生まれ（16歳）</h3>
    {% for member in members_2003 %}
    <div class='grade'>
        <a href="{% url 'nogidb:detail' member.id %}">
        {% if member.thumbnail %}
        <img src='{{ member.thumbnail.url }}' alt={{ member.name }} width=50>
        {% else %}
        <img src='{{ MEDIA_URL }}images/dorayakiman.png' alt='画像はありません' width=50>
        {% endif %}
        <h4>{{ member.name }}</h4>
        </a>        
    </div>
    {% endfor %}

    <h3>2004年度生まれ（15歳）</h3>
    {% for member in members_2004 %}
    <div class='grade'>
        <a href="{% url 'nogidb:detail' member.id %}">
        {% if member.thumbnail %}
        <img src='{{ member.thumbnail.url }}' alt={{ member.name }} width=50>
        {% else %}
        <img src='{{ MEDIA_URL }}images/dorayakiman.png' alt='画像はありません' width=50>
        {% endif %}
        <h4>{{ member.name }}</h4>
        </a>        
    </div>
    {% endfor %}

{% endblock %}

nogidb/templates/nogidb/grade2.html
{% extends 'nogidb/base.html' %}
{% load staticfiles %}

{% block title %}学年別リスト{% endblock %}

{% block style %}
<link href={% static 'css/grade.css' %} rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
<h1>学年別リスト</h1>
<th><a href={% url 'nogidb:grade_condition' 0 %} >活動中のみ</a></th>
<th><a href={% url 'nogidb:grade_condition' 1 %} >卒業生のみ</a></th>
<th><a href={% url 'nogidb:grade' %} >すべて</a></th>

{% for key, value in members %}
<h3>{{ key }}年生まれ</h3>
    {% for member in value %}
    <div class='grade'>
        <a href="{% url 'nogidb:detail' member.id %}">
        {% if member.thumbnail %}
        <img src='{{ member.thumbnail.url }}' alt={{ member.name }} width=50>
        {% else %}
        <img src='{{ MEDIA_URL }}images/dorayakiman.png' alt='画像はありません' width=50>
        {% endif %}
        <h4>{{ member.name }}</h4>
        </a>        
    </div>
    {% endfor %}
{% endfor %}

{% endblock %}

nogidb/templates/nogidb/home.html
{% extends 'nogidb/base.html' %}
{% load staticfiles %}

{% block  title %}ホーム{% endblock %}

{% block style %}
<link href={% static 'css/home.css' %} rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
   <h1 id='top'> <a href={% url 'nogidb:member_list' %}>メンバーリスト</a></h1>
   <h1> <a href={% url 'nogidb:grade' %}>学年別リスト</a></h1>
{% endblock %}

nogidb/templates/nogidb/member_detail.html
{% extends 'nogidb/base.html' %}
{% load staticfiles %}

{% block  title %}{{ member.name }}{% endblock %}

{% block style %}
<link href={% static 'css/detail.css' %} rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
   <h1> <a href=''>{{ member.name }}</a></h1>
   
   {% if member.picture %}
       <img src='{{ MEDIA_URL }}{{ member.picture }}' alt={{ member.name }} width=250>
   
   {% else %}
       <img src='{{ MEDIA_URL }}images/dorayakiman.png' alt='画像はありません' width=250>
   {% endif %}


   <h3>誕生日</h3>{{ member.birthday }}（{{ age }}歳）
   <h3>クラス</h3>{{ member.join_class_display }}
   <h3>活動状況</h3>{{ member.status_display }}
   
{% endblock %}

nogidb/templates/nogidb/member_list.html
{% extends 'nogidb/base.html' %}
{% load staticfiles %}

{% block title %}メンバーリスト{% endblock %}

{% block style %}
<link href={% static 'css/member_list.css' %} rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
  <h1>メンバーリスト</h1>
  <div class='condition'>
    <th><a href="{% url 'nogidb:condition' 0 %}">年齢</a></th>
    <th><a href="{% url 'nogidb:condition' 1 %}">加入時期</a></th>
    <th><a href="{% url 'nogidb:condition' 2 %}">活動状態</a></th>
    <th><a href="{% url 'nogidb:condition' 3 %}">名前順</a></th>
  </div>
  <table>
    <thead>
    <tr>
      <th>名前</th>
      <th>生年月日</th>
      <th>加入時期</th>
      <th>活動状況</th>
    </tr>
    </thead>
    <tbody>
    {# 一覧用 #}
    {% for member in members %}
      <tr>
        <td><a href="{% url 'nogidb:detail' member.id %}">{{ member.name }}</a></td>
        <td>{{ member.birthday }}</td>
        <span><td>{{ member.join_class_display }}</td></span>
        <span><td>{{ member.status_display }}</td></span>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock %}